Repository benthillerkus/SpaceLovers, pull requests merged in 2021-05, with the labels that each got.

#17 Various improvements to the base game
  Asteroid.pde
  Asteroids.pde
  Bullet.pde
  FlyingThing.pde
  Ship.pde
Labels: bug, enhancement

#18 The Big Rewrite
  .gitattributes
  Asteroid.pde
  AsteroidField.pde
  Asteroids.pde
  Bullet.pde
  Camera.pde
  Collision.pde
  FlyingThing.pde
  Game.pde
  GameMenu.pde
  GameObject.pde
  GameWorld.pde
  Gun.pde
  ImageAssets.pde
  InputHelper.pde
  Layer.pde
  Math.pde
  README.md
  Shield.pde
  Ship.pde
  data/Art/Asteroid-Large.png
  data/Art/Asteroid-Medium-1.png
  data/Art/Asteroid-Medium-2.png
  data/Art/Asteroid-Medium-3.png
  data/Art/Asteroid-Small-1.png
  data/Art/Asteroid-Small-2.png
  data/Art/Asteroid-Small-3.png
  data/Art/Asteroid-Tiny-1.png
  data/Art/Background.png
  data/Art/Comet.png
  data/Art/Effect-Explosion-1.png
  data/Art/Effect-Muzzle-Medium-1.png
  data/Art/Effect-Muzzle-Medium-2.png
  data/Art/Effect-Muzzle-Tiny-1.png
  data/Art/Effect-Projectile-Tiny.png
  data/Art/Gun.png
  data/Art/Originals.afdesign
  data/Art/Shield-Active.png
  data/Art/Shield-Inactive.png
  data/Art/Shield.png
  data/Art/Ship.png
  data/Art/Thruster.png
  data/Fonts/VT323-Regular.ttf
  data/Fonts/good_times_rg.ttf
  data/GameplaySound/asteroidHit.mp3
  data/GameplaySound/bang.mp3
  data/GameplaySound/lose.mp3
  data/GameplaySound/thrusterHigh.mp3
  data/GameplaySound/thrusterLow.mp3
  data/GameplaySound/win.mp3
  data/MenuSound/MachineryMenuSound.mp3
  data/MenuSound/MenuBackTines.mp3
  data/MenuSound/MenuForwardTines.mp3
  data/SANIC.mp3
Labels: good first issue

#26 Setze das Spiel zurück ins Menü, nachdem er / sie starb
  AsteroidField.pde
  Asteroids.pde
  Game.pde
  GameMenu.pde
  GameObject.pde
  Gun.pde
  Layer.pde
  Ship.pde
Labels: bug

#31 Add a basic mission system
  .gitattributes
  AsteroidField.pde
  Asteroids.pde
  Camera.pde
  Collision.pde
  Game.pde
  GameMenu.pde
  GameObject.pde
  Gun.pde
  Hud.pde
  Layer.pde
  Missions.pde
  Shield.pde
  Ship.pde
  Stats.pde
  data/Art/Gun.png
  data/Art/Shield.png
  data/Fonts/VT323-Regular.ttf
  data/Fonts/good_times_rg.ttf
Labels: enhancement

#37 Add game over screens
  Button.pde
  Game.pde
  GameMenu.pde
  GameOverScreen.pde
  Layer.pde
  Missions.pde
  Shield.pde
  Ship.pde
  Stats.pde
Labels: enhancement

#38 Add an in game HUD
  Event.pde
  Game.pde
  GameObject.pde
  GameOverScreen.pde
  Hud.pde
  Missions.pde
  Player.pde
  Ship.pde
  Stats.pde
Labels: enhancement

#15 Füge Soundeffekte ein
  Assets.pde
  AsteroidField.pde
  Event.pde
  Game.pde
  GameMenu.pde
  Gun.pde
  Ship.pde
Labels: enhancement

#27 Implement Shield & Thruster
  Asteroids.pde
  Gun.pde
  Hud.pde
  Missions.pde
  README.md
  Shield.pde
  Ship.pde
  ShipComponent.pde
  Thruster.pde
Labels: bug, enhancement, help wanted

#44 Add basic effects
  Assets.pde
  Event.pde
  Gun.pde
  Hud.pde
  Shield.pde
  Ship.pde
  ShipComponent.pde
  Thruster.pde
Labels: enhancement

#45 Add some more hit reactions
  Collision.pde
  Game.pde
  GameMenu.pde
  Ship.pde
  ShipComponent.pde
  Thruster.pde
Labels: enhancement

#53 Fix audio
  .github/workflows/make-release.yml
  .github/workflows/processing-build.yml
  Assets.pde
  Asteroids.pde
  Gun.pde
Labels: bug

#56 Create LICENSE
  .github/workflows/make-release.yml
  LICENSE
  README.md
  data/Art/CC BY-NC-SA 4.0.txt
  data/GameplaySound/CC BY-NC-SA 4.0.txt
  data/MenuSound/CC BY-NC-SA 4.0.txt
Labels: documentation, question
